[package]
name = "rustdrive-sim"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rustdrive-pipeline = { path = "../pipeline" }
serde.workspace = true
serde_json.workspace = true
rustdrive-core = { path = "../core" }

[lints]
workspace = true

[[bin]]
name = "rustdrive"
path = "src/main.rs"
