[package]
name = "rustdriving-sim"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rustdriving-pipeline = { path = "../pipeline" }
serde.workspace = true
serde_json.workspace = true
rustdriving-core = { path = "../core" }
rustdriving-routing = { path = "../routing" }

[lints]
workspace = true

[[bin]]
name = "rustdriving"
path = "src/main.rs"
