[package]
name = "rustdriving-dataset-eval"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rustdriving-core = { path = "../core" }
rustdriving-perception = { path = "../perception" }
rustdriving-localization = { path = "../localization" }
serde_json.workspace = true

[lints]
workspace = true
